include: package:pedantic/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    prefer_void_to_null: true
    always_put_required_named_parameters_first: true
    avoid_returning_this: true
    avoid_returning_null: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    directives_ordering: true
    exhaustive_cases: true
    join_return_with_assignment: true
    no_runtimeType_toString: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true
    unnecessary_statements: true
    throw_in_finally: true
    test_types_in_equals: true
    prefer_relative_imports: true
    no_adjacent_strings_in_list: true
    literal_only_boolean_expressions: true
    list_remove_unrelated_type: true
    iterable_contains_unrelated_type: true
    invariant_booleans: true
    hash_and_equals: true
    empty_statements: true
    control_flow_in_finally: true
    cancel_subscriptions: true
    avoid_type_to_string: true
    #avoid_dynamic_calls: true
    close_sinks: true
    avoid_renaming_method_parameters: true

analyzer:
  plugins:
    - dart_code_metrics
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/bindings/**

dart_code_metrics:
  anti-patterns:
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - lib/src/bindings/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - member-ordering
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
