name: opus_codec
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  ffigen: ^2.4.1
  pedantic: ^1.10.0
  dart_code_metrics: ^3.0.0

ffigen:
  name: "LibOpus"
  description: "Bindings to opus"
  array-workaround: true
  output: "lib/src/bindings/opus_bindings.dart"
  headers:
    entry-points:
      - "headers/opus_custom.h"
      - "headers/opus_defines.h"
      - "headers/opus_multistream.h"
      - "headers/opus_projection.h"
      - "headers/opus_types.h"
      - "headers/opus.h"
